---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by flyfish.
--- DateTime: 2025/3/2 16:35
---


-- 比较线程标示与锁中的标示是否一致
if(redis.call('get', KEYS[1]) == ARGV[1]) then
    -- 释放锁
    return redis.call('del', KEYS[1])
end
return 0